version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "99:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
